#Start of the Makefile
all: testSmite.o
	gcc -std=c99 -o testSmite testSmite.o -I.

#testSmite.o: testSmite.c
#	gcc -std=c99 -Wall -g -c testSmite.c -I.

clean:
	rm *.o testSmite

##End of the Makefile

